jobs:
- job: 'Build site'

  trigger:
  - site

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '>= 2.5'

  - script: ./scripts/access-theme.sh
    env:
      THEME_SSH_KEY: $(THEME_SSH_KEY)
    displayName: 'Set up SSH'

  - script: |
      gem install bundler jekyll
      bundle install --retry=3 --jobs=4
    displayName: 'Install dependencies'

  - script: jekyll build --future
    displayName: 'Run Jekyll'


- job: 'Publish site'
  dependsOn: 'Build site'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

  trigger:
  - site

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: ./scripts/access-theme.sh
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
    displayName: 'Push to master'
